StaffTrainee/Controllers/CategoriesController.cs
using Microsoft.Ajax.Utilities;
using StaffTrainee.Models;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace StaffTrainee.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private ApplicationDbContext _context;
        public CategoriesController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Categories

        public ActionResult Index(string searchString)
        {
            var categoriesInDb = _context.Categories.ToList();



            if (!searchString.IsNullOrWhiteSpace())
            {
                categoriesInDb = _context.Categories.Where(c => c.Name.Contains(searchString)).ToList();
            }

            return View(categoriesInDb);
        }

        [HttpGet]
        [Authorize(Roles = "Staff")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Staff")]
        public ActionResult Create(Category model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (_context.Categories.Any(c => c.Name.Contains(model.Name)))
            {
                ModelState.AddModelError("", "Category Name alreay exists");
                return View(model);
            }
            var category = new Category
            {
                Name = model.Name,
                Description = model.Description
            };

            _context.Categories.Add(category);

            _context.SaveChanges();

            return RedirectToAction("Index");
        }


        [HttpGet]
        [Authorize(Roles = "Staff")]
        public ActionResult Delete(int? id)
        {
            //var categoriesId = User.Identity.GetUserId();

            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var categoryinDb = _context.Categories
                //.Where(c => c.Id.Equals(userId))
                .SingleOrDefault(c => c.Id == id);

            if (categoryinDb == null) return HttpNotFound();

            _context.Categories.Remove(categoryinDb);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpGet]
        [Authorize(Roles = "Staff")]
        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var categoryInDb = _context.Categories.SingleOrDefault(c => c.Id == id);

            if (categoryInDb == null) return HttpNotFound();

            return View(categoryInDb);
        }
        [HttpPost]
        [Authorize(Roles = "Staff")]
        public ActionResult Edit(Category category)
        {
            var categoryInDb = _context.Categories.SingleOrDefault(c => c.Id == category.Id);

            if (!ModelState.IsValid)
            {
                return View(category);
            }
            if (_context.Categories.Any(c => c.Name.Contains(category.Name)))
            {
                ModelState.AddModelError("", "Category Name alreay exists");
                return View(category);
            }


            categoryInDb.Description = category.Description;
            categoryInDb.Name = category.Name;


            _context.SaveChanges();

            return RedirectToAction("Index");


        }
    }
}

StaffTrainee/Controllers/UserInfosController.cs
using StaffTrainee.Models;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace StaffTrainee.Controllers
{
    [Authorize]
    public class UserInfosController : Controller
    {
        private ApplicationDbContext _context;
        public UserInfosController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: UserInfos
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var userInfo = _context.UserInfos.SingleOrDefault(u => u.UserId.Equals(userId));

            if (userInfo == null) return HttpNotFound();
            return View(userInfo);
        }

        [HttpGet]
        public ActionResult Edit()
        {
            var userId = User.Identity.GetUserId();
            var userInfo = _context.UserInfos.SingleOrDefault(u => u.UserId.Equals(userId));

            if (userInfo == null) return HttpNotFound();
            return View(userInfo);
        }

        [HttpPost]
        public ActionResult Edit(UserInfo userInfo)
        {
            if (!ModelState.IsValid)
            {
                return View(userInfo);
            }

            var userInfoInDb = _context.UserInfos
              .SingleOrDefault(u => u.UserId.Equals(userInfo.UserId));

            if (userInfoInDb == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            userInfoInDb.FullName = userInfo.FullName;
            userInfoInDb.Phone = userInfo.Phone;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        //[Authorize(Roles = "Admin")]
        //public ActionResult Delete(string id)
        //{

        //    var userInfo = _context.UserInfos

        //        .SingleOrDefault(s => s.UserId == id);

        //    _context.Users.Remove(userInfo);
        //    _context.SaveChanges();


        //    return RedirectToAction("GetStaffs");
        //}






        //[HttpGet]

        //public ActionResult Delete(string id)
        //{
        //    //var userId = User.Identity.GetUserId();

        //    if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

        //    var userInfo = _context.UserInfos
        //        //.Where(t => t.UserId.Equals(userId))
        //        .SingleOrDefault(t => t.UserId.Equals(id));

        //    if (userInfo == null) return HttpNotFound();

        //    _context.UserInfos.Remove(userInfo);
        //    _context.SaveChanges();

        //    return RedirectToAction("Index");
        //}










    }
}

StaffTrainee/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">


                    @if (User.IsInRole("Admin"))
                    {
                <li>@Html.ActionLink("My User Info", "Index", "UserInfos")</li>
                
               
                    }


                    @if (User.IsInRole("Staff"))
                    {
                <li>@Html.ActionLink("Course Categories", "Index", "Categories")</li>
                <li>@Html.ActionLink("Courses", "Index", "Courses")</li>
               
                }




                    @if (User.IsInRole("Trainer"))
                    {

                <li>@Html.ActionLink("My User Info", "Index", "UserInfos")</li>
                <li>@Html.ActionLink("My Courses", "MineTrainer", "Courses")</li>

                    }
                    @if (User.IsInRole("Trainee"))
                    {

                <li>@Html.ActionLink("Available Courses", "Index", "Courses")</li>
                <li>@Html.ActionLink("My User Info", "Index", "UserInfos")</li>
                <li>@Html.ActionLink("My Courses", "MineTrainee", "Courses")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
           
            <p>
                @Html.ActionLink(
                     "HoangDung's ASP.NET ",
                     "Index",
                     "Home",
                    null,
                     new { @class = "Link" }
                   )&copy; @DateTime.Now.Year. All Rights Reserved.
            </p>
            <p>Sponsor for this System: Mr.Vinh</p>

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>